/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Getting Started',
//       items: ['installation', 'start-engine', 'create-app'],
//     },
//   ],
// };
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'installation', 
        'start-engine', 
        'create-app',
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'add-bkg-img', 
        'add-img',
      ],
    },
  ]
};    
module.exports = sidebars;
